// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/api/api.proto

package go_micro_service_api

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Api service

type ApiService interface {
	Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (Api_StreamService, error)
	PingPong(ctx context.Context, opts ...client.CallOption) (Api_PingPongService, error)
}

type apiService struct {
	c    client.Client
	name string
}

func NewApiService(name string, c client.Client) ApiService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "go.micro.service.api"
	}
	return &apiService{
		c:    c,
		name: name,
	}
}

func (c *apiService) Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Api.Call", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiService) Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (Api_StreamService, error) {
	req := c.c.NewRequest(c.name, "Api.Stream", &StreamingRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	if err := stream.Send(in); err != nil {
		return nil, err
	}
	return &apiServiceStream{stream}, nil
}

type Api_StreamService interface {
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Recv() (*StreamingResponse, error)
}

type apiServiceStream struct {
	stream client.Stream
}

func (x *apiServiceStream) Close() error {
	return x.stream.Close()
}

func (x *apiServiceStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *apiServiceStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *apiServiceStream) Recv() (*StreamingResponse, error) {
	m := new(StreamingResponse)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

func (c *apiService) PingPong(ctx context.Context, opts ...client.CallOption) (Api_PingPongService, error) {
	req := c.c.NewRequest(c.name, "Api.PingPong", &Ping{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	return &apiServicePingPong{stream}, nil
}

type Api_PingPongService interface {
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Ping) error
	Recv() (*Pong, error)
}

type apiServicePingPong struct {
	stream client.Stream
}

func (x *apiServicePingPong) Close() error {
	return x.stream.Close()
}

func (x *apiServicePingPong) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *apiServicePingPong) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *apiServicePingPong) Send(m *Ping) error {
	return x.stream.Send(m)
}

func (x *apiServicePingPong) Recv() (*Pong, error) {
	m := new(Pong)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Api service

type ApiHandler interface {
	Call(context.Context, *Request, *Response) error
	Stream(context.Context, *StreamingRequest, Api_StreamStream) error
	PingPong(context.Context, Api_PingPongStream) error
}

func RegisterApiHandler(s server.Server, hdlr ApiHandler, opts ...server.HandlerOption) error {
	type api interface {
		Call(ctx context.Context, in *Request, out *Response) error
		Stream(ctx context.Context, stream server.Stream) error
		PingPong(ctx context.Context, stream server.Stream) error
	}
	type Api struct {
		api
	}
	h := &apiHandler{hdlr}
	return s.Handle(s.NewHandler(&Api{h}, opts...))
}

type apiHandler struct {
	ApiHandler
}

func (h *apiHandler) Call(ctx context.Context, in *Request, out *Response) error {
	return h.ApiHandler.Call(ctx, in, out)
}

func (h *apiHandler) Stream(ctx context.Context, stream server.Stream) error {
	m := new(StreamingRequest)
	if err := stream.Recv(m); err != nil {
		return err
	}
	return h.ApiHandler.Stream(ctx, m, &apiStreamStream{stream})
}

type Api_StreamStream interface {
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*StreamingResponse) error
}

type apiStreamStream struct {
	stream server.Stream
}

func (x *apiStreamStream) Close() error {
	return x.stream.Close()
}

func (x *apiStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *apiStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *apiStreamStream) Send(m *StreamingResponse) error {
	return x.stream.Send(m)
}

func (h *apiHandler) PingPong(ctx context.Context, stream server.Stream) error {
	return h.ApiHandler.PingPong(ctx, &apiPingPongStream{stream})
}

type Api_PingPongStream interface {
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Pong) error
	Recv() (*Ping, error)
}

type apiPingPongStream struct {
	stream server.Stream
}

func (x *apiPingPongStream) Close() error {
	return x.stream.Close()
}

func (x *apiPingPongStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *apiPingPongStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *apiPingPongStream) Send(m *Pong) error {
	return x.stream.Send(m)
}

func (x *apiPingPongStream) Recv() (*Ping, error) {
	m := new(Ping)
	if err := x.stream.Recv(m); err != nil {
		return nil, err
	}
	return m, nil
}
