// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/offer/offer.proto

package go_micro_service_offer

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Offer service

type OfferService interface {
	SetOffer(ctx context.Context, in *OfferRequest, opts ...client.CallOption) (*Response, error)
	GetOffer(ctx context.Context, in *OfferRequest, opts ...client.CallOption) (*Response, error)
}

type offerService struct {
	c    client.Client
	name string
}

func NewOfferService(name string, c client.Client) OfferService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "go.micro.service.offer"
	}
	return &offerService{
		c:    c,
		name: name,
	}
}

func (c *offerService) SetOffer(ctx context.Context, in *OfferRequest, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Offer.SetOffer", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *offerService) GetOffer(ctx context.Context, in *OfferRequest, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Offer.GetOffer", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Offer service

type OfferHandler interface {
	SetOffer(context.Context, *OfferRequest, *Response) error
	GetOffer(context.Context, *OfferRequest, *Response) error
}

func RegisterOfferHandler(s server.Server, hdlr OfferHandler, opts ...server.HandlerOption) error {
	type offer interface {
		SetOffer(ctx context.Context, in *OfferRequest, out *Response) error
		GetOffer(ctx context.Context, in *OfferRequest, out *Response) error
	}
	type Offer struct {
		offer
	}
	h := &offerHandler{hdlr}
	return s.Handle(s.NewHandler(&Offer{h}, opts...))
}

type offerHandler struct {
	OfferHandler
}

func (h *offerHandler) SetOffer(ctx context.Context, in *OfferRequest, out *Response) error {
	return h.OfferHandler.SetOffer(ctx, in, out)
}

func (h *offerHandler) GetOffer(ctx context.Context, in *OfferRequest, out *Response) error {
	return h.OfferHandler.GetOffer(ctx, in, out)
}
